# 【10.10】try-catch 中抛出一个错误

---

在使用 try-catch 时经常会处理异常问题。

```javascript
let count = 100;
try {
  if (count < 100) {
    throw "哇喔，错误了";
  } else {
    // work well.
  }
} catch (e) {
  console.log(e);
}
```

```javascript
let count = 100;
try {
  if (count < 100) {
    throw new Error("哇喔，错误了");
  } else {
    // work well.
  }
} catch (e) {
  console.log(e);
}
```

以上 throw 用了两种做法，你觉得那种好，为什么？

---

The second one will be better, it consloe.log the your own error problem and at the same time it tell you where and why you are wrong.

---

@MyColourfulLife

## throw 语句

throw 语句用来抛出一个用户自定义的异常。当前函数的执行将被停止（throw 之后的语句将不会执行），并且控制将被传递到调用堆栈中的第一个 catch 块。如果调用者函数中没有 catch 块，程序将会终止。

显然，throw 的作用就是抛出异常，尽管 throw 可以扔出来任意类型的数据，但是扔个字符串出来，不知道的人可能不觉得那是一个错误。而如果扔出来一个错误对象，明白人一看就知道那是一个错误，可以看到更多的错误信息，比如错误堆栈信息等。方便对错误进行处理。

## Error 对象

JavaScript 解析或执行时，一旦发生错误，引擎就会抛出一个错误对象。JavaScript 原生提供一个 Error 构造函数，所有抛出的错误都是这个构造函数的实例

Error 构造函数接受一个参数，表示错误提示，可以从实例的 message 属性读到这个参数。
根据语言标准，Error 对象的实例必须有 message 属性，表示出错时的提示信息，其他属性则没有提及。大多数 JavaScript 引擎，对 Error 实例还提供 name 和 stack 属性，分别表示错误的名称和错误的堆栈

利用 name 和 message 这两个属性，可以对发生什么错误有一个大概的了解。
比如案例中的抛出 error 对象那个 打印时就有 ERROR(name), "哇喔，错误了 "(message) 以及堆栈信息等

---

Error 对象是最一般的错误类型，在它的基础上，JavaScript 还定义了其他 6 种错误。

- SyntaxError 语法错误
- ReferenceError 引用错误
- RangeError 范围错误
- TypeError 类型错误
- URIError URI 错误
- EvalError 执行错误 该错误类型已经不再在 ES5 中出现了，只是为了保证与以前代码兼容，才继续保留。

既然是处理错误，错误类型越明确，对开发越具有指导意义，因此抛出异常时，应尽量明确错误类型，而不仅仅只是抛出一个 ERROR 类型

另外，用户也可以自定义错误对象， 自定义的错误对象，最好也要继承 ERROR 对象。

MDN 给出的[例子](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/throw) 没有继承 ERROR 对象，打印出的结果定义的啥，就是啥，打印结果也没有堆栈信息。因此最好继承 ERROR 对象
可以先不用理解怎么继承，先看例子会用即可。

```javascript
//定义
function UserError(message) {
  this.message = message || "默认信息";
  this.name = "UserError";
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;
//使用
new UserError("这是自定义的错误！");
```

---

@MyColourfulLife 的回复很详细了。

在进行错误处理过程，有一些重要的错误是需要函数调用栈信息的才能方便定位问题。new Error 会自动提供调用栈信息。

```javascript
Error: 哇喔，发生错误了
    at Object.<anonymous> (/Users/youngxu/Desktop/sample.js:2:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

throw 语句用来显性抛出异常。
new Error (message) 语句是在当发生异常情况时，Error 对象把 message 参数的内容当做 message 的属性值，以提供关于异常的细节的错误消息。

throw 后用 new Error（）可以帮助更便利地 debug。
