# 【10.10】try-catch中抛出一个错误

---

在使用try-catch时经常会处理异常问题。

```javascript
let count = 100;
try {
   if ( count < 100) {
     throw "哇喔，错误了";
  } else {
     // work well.
  }
} catch (e) {
    console.log(e);
}

```

```javascript
let count = 100;
try {
   if ( count < 100) {
     throw  new Error("哇喔，错误了");
  } else {
     // work well.
  }
} catch (e) {
    console.log(e);
}

```

以上throw用了两种做法，你觉得那种好，为什么？

---

The second one will be better, it consloe.log the your own error problem and at the same time it tell you where and why you are wrong.

---

@MyColourfulLife

## throw 语句

throw 语句用来抛出一个用户自定义的异常。当前函数的执行将被停止（throw之后的语句将不会执行），并且控制将被传递到调用堆栈中的第一个 catch 块。如果调用者函数中没有catch块，程序将会终止。

显然，throw的作用就是抛出异常，尽管throw可以扔出来任意类型的数据，但是扔个字符串出来，不知道的人可能不觉得那是一个错误。而如果扔出来一个错误对象，明白人一看就知道那是一个错误，可以看到更多的错误信息，比如错误堆栈信息等。方便对错误进行处理。

## Error对象

JavaScript解析或执行时，一旦发生错误，引擎就会抛出一个错误对象。JavaScript原生提供一个Error构造函数，所有抛出的错误都是这个构造函数的实例

Error构造函数接受一个参数，表示错误提示，可以从实例的message属性读到这个参数。
根据语言标准，Error对象的实例必须有message属性，表示出错时的提示信息，其他属性则没有提及。大多数JavaScript引擎，对Error实例还提供name和stack属性，分别表示错误的名称和错误的堆栈

利用name和message这两个属性，可以对发生什么错误有一个大概的了解。
比如案例中的抛出 error对象那个 打印时就有 ERROR(name), "哇喔，错误了 "(message) 以及堆栈信息等

---

Error对象是最一般的错误类型，在它的基础上，JavaScript还定义了其他6种错误。

- SyntaxError 语法错误
- ReferenceError 引用错误
- RangeError 范围错误
- TypeError 类型错误
- URIError URI错误
- EvalError 执行错误 该错误类型已经不再在ES5中出现了，只是为了保证与以前代码兼容，才继续保留。

既然是处理错误，错误类型越明确，对开发越具有指导意义，因此抛出异常时，应尽量明确错误类型，而不仅仅只是抛出一个ERROR类型

另外，用户也可以自定义错误对象， 自定义的错误对象，最好也要继承ERROR对象。

MDN给出的[例子](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/throw) 没有继承ERROR对象，打印出的结果定义的啥，就是啥，打印结果也没有堆栈信息。因此最好继承ERROR对象
可以先不用理解怎么继承，先看例子会用即可。

```javascript
//定义
function UserError(message) {
   this.message = message || "默认信息";
   this.name = "UserError";
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;
//使用
new UserError("这是自定义的错误！");

```

---

@MyColourfulLife 的回复很详细了。

在进行错误处理过程，有一些重要的错误是需要函数调用栈信息的才能方便定位问题。new Error会自动提供调用栈信息。

```javascript
Error: 哇喔，发生错误了
    at Object.<anonymous> (/Users/youngxu/Desktop/sample.js:2:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

throw语句用来显性抛出异常。
new Error (message) 语句是在当发生异常情况时，Error对象把message参数的内容当做message的属性值，以提供关于异常的细节的错误消息。

throw后用new Error（）可以帮助更便利地debug。
